# Console UI Command Contracts
# Defines the interface between the console UI and Phase I operations

openapi: 3.0.0
info:
  title: Console UI Command Interface
  version: 1.0.0
  description: API contracts for console-based task management commands

paths:
  /command/add:
    post:
      summary: Add a new task
      description: Creates a new task with the specified title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the task to be added
                  example: "Buy groceries"
              required:
                - title
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier of the created task
                    example: "123"
                  title:
                    type: string
                    description: Title of the created task
                    example: "Buy groceries"
                  completed:
                    type: boolean
                    description: Whether the task is completed
                    example: false
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Title is required"

  /command/list:
    get:
      summary: List all tasks
      description: Retrieves all tasks with their status
      responses:
        '200':
          description: List of tasks retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier of the task
                          example: "123"
                        title:
                          type: string
                          description: Title of the task
                          example: "Buy groceries"
                        completed:
                          type: boolean
                          description: Whether the task is completed
                          example: false
        '204':
          description: No tasks found

  /command/complete:
    put:
      summary: Mark task as completed
      description: Updates the status of a task to completed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID of the task to complete
                  example: "123"
              required:
                - id
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier of the task
                    example: "123"
                  title:
                    type: string
                    description: Title of the task
                    example: "Buy groceries"
                  completed:
                    type: boolean
                    description: Whether the task is completed
                    example: true
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Task with ID 123 not found"

  /command/delete:
    delete:
      summary: Delete a task
      description: Removes a task permanently
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID of the task to delete
                  example: "123"
              required:
                - id
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Task with ID 123 not found"

  /command/update:
    put:
      summary: Update a task
      description: Modifies an existing task's properties
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID of the task to update
                  example: "123"
                title:
                  type: string
                  description: New title for the task (optional)
                  example: "Updated task title"
              required:
                - id
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier of the task
                    example: "123"
                  title:
                    type: string
                    description: Updated title of the task
                    example: "Updated task title"
                  completed:
                    type: boolean
                    description: Whether the task is completed
                    example: false
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Task with ID 123 not found"